export const CAR_MODELS_BY_BRAND: Record<string, string[]> = {
  BMW: [
    '1 Series',
    '2 Series',
    '3 Series',
    '4 Series',
    '5 Series',
    '6 Series',
    '7 Series',
    '8 Series',
    'X1',
    'X2',
    'X3',
    'X4',
    'X5',
    'X6',
    'X7',
    'Z3',
    'Z4',
    'i3',
    'i4',
    'i7',
    'i8',
    'iX',
    'iX3',
  ],
  'Mercedes-Benz': [
    'A-Class',
    'B-Class',
    'C-Class',
    'CLA',
    'CLS',
    'E-Class',
    'S-Class',
    'G-Class',
    'GLA',
    'GLB',
    'GLC',
    'GLE',
    'GLS',
    'ML',
    'SL',
    'SLK',
    'AMG GT',
    'Vito',
    'Sprinter',
  ],
  Audi: [
    'A1',
    'A3',
    'A4',
    'A5',
    'A6',
    'A7',
    'A8',
    'Q2',
    'Q3',
    'Q5',
    'Q7',
    'Q8',
    'TT',
    'R8',
    'e-tron GT',
    'e-tron',
    'RS3',
    'RS4',
    'RS5',
    'RS6',
    'RS7',
  ],
  Volkswagen: [
    'Golf',
    'Polo',
    'Passat',
    'Jetta',
    'Tiguan',
    'Touareg',
    'Touran',
    'Sharan',
    'Beetle',
    'Arteon',
    'T-Cross',
    'T-Roc',
    'ID.3',
    'ID.4',
    'ID.5',
    'ID.7',
  ],
  Toyota: [
    'Corolla',
    'Camry',
    'Prius',
    'RAV4',
    'Highlander',
    'Land Cruiser',
    'Prado',
    'Yaris',
    'Auris',
    'Avensis',
    'C-HR',
    'Aygo',
    'Supra',
    'bZ4X',
  ],
  Honda: [
    'Civic',
    'Accord',
    'CR-V',
    'HR-V',
    'Pilot',
    'Odyssey',
    'Fit',
    'Insight',
    'Ridgeline',
    'Passport',
    'Element',
    'Jazz',
    'City',
  ],
  Ford: [
    'Focus',
    'Fiesta',
    'Mondeo',
    'Escape',
    'Explorer',
    'F-150',
    'Mustang',
    'Edge',
    'Expedition',
    'Ranger',
    'Transit',
    'EcoSport',
    'Puma',
    'Kuga',
  ],
  Chevrolet: [
    'Cruze',
    'Malibu',
    'Impala',
    'Equinox',
    'Traverse',
    'Tahoe',
    'Suburban',
    'Silverado',
    'Camaro',
    'Corvette',
    'Bolt',
    'Aveo',
    'Captiva',
    'Lacetti',
  ],
  Nissan: [
    'Altima',
    'Sentra',
    'Maxima',
    'Rogue',
    'Murano',
    'Pathfinder',
    'Armada',
    'Frontier',
    'Titan',
    '370Z',
    'GT-R',
    'Leaf',
    'Ariya',
    'Micra',
    'Qashqai',
    'X-Trail',
  ],
  Hyundai: [
    'Elantra',
    'Sonata',
    'Accent',
    'Tucson',
    'Santa Fe',
    'Palisade',
    'Venue',
    'Veloster',
    'Genesis',
    'Ioniq',
    'Kona',
    'Nexo',
    'i10',
    'i20',
    'i30',
  ],
  Kia: [
    'Forte',
    'Optima',
    'Rio',
    'Sportage',
    'Sorento',
    'Telluride',
    'Soul',
    'Stinger',
    'Niro',
    'Seltos',
    'Carnival',
    'Picanto',
    'Ceed',
    'XCeed',
    'EV6',
  ],
  Mazda: ['Mazda3', 'Mazda6', 'CX-3', 'CX-30', 'CX-5', 'CX-9', 'MX-5', 'CX-50', 'Mazda2', 'RX-8', 'MX-30'],
  Lexus: ['IS', 'ES', 'GS', 'LS', 'UX', 'NX', 'GX', 'LX', 'RX', 'LC', 'RC', 'CT', 'RZ', 'LFA'],
  Infiniti: ['Q50', 'Q60', 'Q70', 'QX30', 'QX50', 'QX60', 'QX70', 'QX80', 'G35', 'G37', 'FX35', 'FX37'],
  Volvo: ['S60', 'S90', 'V40', 'V60', 'V90', 'XC40', 'XC60', 'XC90', 'C30', 'C70', 'XC70', 'EX30', 'EX90'],
  Tesla: ['Model S', 'Model 3', 'Model X', 'Model Y', 'Cybertruck', 'Roadster'],
  Jeep: [
    'Wrangler',
    'Grand Cherokee',
    'Cherokee',
    'Compass',
    'Renegade',
    'Gladiator',
    'Patriot',
    'Liberty',
    'Commander',
  ],
  'Land Rover': [
    'Range Rover',
    'Range Rover Sport',
    'Range Rover Evoque',
    'Range Rover Velar',
    'Discovery',
    'Discovery Sport',
    'Defender',
    'Freelander',
  ],
  Porsche: ['911', 'Cayenne', 'Macan', 'Panamera', 'Taycan', 'Boxster', 'Cayman', '718', '944', '928'],
  Subaru: ['Impreza', 'Legacy', 'Outback', 'Forester', 'Ascent', 'Crosstrek', 'WRX', 'BRZ', 'Solterra'],
  Mitsubishi: ['Lancer', 'Outlander', 'Eclipse Cross', 'Mirage', 'Pajero', 'ASX', 'L200', 'Galant', 'Colt'],
  Renault: ['Clio', 'Megane', 'Scenic', 'Kadjar', 'Captur', 'Koleos', 'Duster', 'Logan', 'Sandero', 'Talisman', 'Zoe'],
  Peugeot: ['208', '308', '508', '2008', '3008', '5008', 'Partner', '206', '207', '307', '407', 'e-208', 'e-2008'],
  Skoda: ['Octavia', 'Fabia', 'Superb', 'Kodiaq', 'Karoq', 'Kamiq', 'Scala', 'Rapid', 'Yeti', 'Enyaq'],
  Opel: ['Astra', 'Corsa', 'Insignia', 'Mokka', 'Crossland', 'Grandland', 'Combo', 'Vectra', 'Zafira'],
  Fiat: ['500', '500X', '500L', 'Panda', 'Punto', 'Tipo', 'Doblo', 'Fiorino', '500e', 'Ducato'],
  Mini: ['Cooper', 'Countryman', 'Clubman', 'Paceman', 'Roadster', 'Coupe', 'Electric'],
  Suzuki: ['Swift', 'Vitara', 'SX4', 'Jimny', 'Baleno', 'Ignis', 'Celerio', 'Grand Vitara', 'Splash'],
  Seat: ['Ibiza', 'Leon', 'Arona', 'Ateca', 'Tarraco', 'Alhambra', 'Toledo', 'Altea', 'Mii'],
  Citroën: ['C1', 'C3', 'C4', 'C5', 'C3 Aircross', 'C5 Aircross', 'Berlingo', 'Picasso', 'Xsara', 'ë-C4'],
  'Alfa Romeo': ['Giulia', 'Stelvio', 'Giulietta', 'MiTo', '159', '156', '147', '4C', 'Tonale'],
  Jaguar: ['XE', 'XF', 'XJ', 'F-Pace', 'E-Pace', 'I-Pace', 'F-Type', 'XK', 'S-Type'],
  'ВАЗ (Lada)': [
    'Granta',
    'Kalina',
    'Priora',
    'Largus',
    'Vesta',
    'XRAY',
    'Niva',
    '2101',
    '2102',
    '2103',
    '2104',
    '2105',
    '2106',
    '2107',
    '2108',
    '2109',
    '2110',
    '2111',
    '2112',
    '2113',
    '2114',
    '2115',
  ],
};

export const getModelsForBrand = (brand: string): string[] => {
  return CAR_MODELS_BY_BRAND[brand] || [];
};
