export const routes = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  EMAIL_CONFIRMATION: '/email-confirmation',
  PHONE_CONFIRMATION: '/phone-confirmation',
  RESET_PASSWORD: '/reset-password',
  PROFILE: '/profile',
  VEHICLES: '/vehicles',
  VEHICLE_DETAIL: '/vehicles/:id',
  VEHICLE_CREATE: '/vehicles/create',
  VEHICLE_EDIT: '/vehicles/:id/edit',
  MY_VEHICLES: '/my-vehicles',
  FAVORITES: '/favorites',
  MESSAGES: '/messages',
  MESSAGE_CONVERSATION: '/messages/:conversationId',
  NOT_FOUND: '*',
  CAR_DETAILS: "/car/:id",
  MY_LISTINGS: "/my-listings",
  EDIT_LISTING: "/edit-listing/:id",
  API: {
    BASE: import.meta.env.VITE_BASE_API_URL,
    USERS: '/users',
    VEHICLES: '/vehicles',
    FAVORITES: '/favorites',
    USER_MESSAGES: '/user_messages',
    COMMENTS: '/comments',
    REPORTS: '/reports',
  },
};
