export const routes = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  PROFILE: '/profile',
  NOT_FOUND: '*',
  CREATE: "/create",
  CAR_DETAILS: "/car/:id",
  MY_LISTINGS: "/my-listings",
  EDIT_LISTING: "/edit-listing/:id",
  API: {
    BASE: import.meta.env.VITE_BASE_API_URL,
    USERS: '/users',
    VEHICLES: '/vehicles',
    FAVORITES: '/favorites',
    USER_MESSAGES: '/user_messages',
    COMMENTS: '/comments',
    REPORTS: '/reports',
  },
};
